#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="$HOME/.nvm/versions/node/v20.19.2/bin:/usr/local/bin:$PATH"

# Perform lint check on files in the staging area through .lintstagedrc configuration
pnpm exec lint-staged